<a href="https://colab.research.google.com/github/Jyotri-9/jyoti_CAR_2201206027/blob/main/1st_PYTHON_29_02_2004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=100
print("a=",a)

a= 100


In [ ]:
a=12
b=12
c=2022
print(a,b,c,sep="-")

12-12-2022


In [ ]:
a=input('Enter first No:')
b=input('Enter Second No:')
c=a+b
print(c)


Enter first No:567
Enter Second No:76767
56776767


In [ ]:
a=input('Enter First No:')
b=input('Enter Second No:')
c=a+b
print(c)

Enter First No:678
Enter Second No:
678


In [ ]:
n=input('Enter your name')
print('myself',n)

Enter your namejyoti
myself jyoti


In [ ]:
#Arithimetic operators
a=2
b=5
c=a+b
print('a+b=',c)
d=a-b
print('a-b=',d)
e=a*b
print('a*b=',e)
f=a/b
print('a/b=',f)
g=a%b
print('a%b=',g)
h=a//b
print('a-b',h)
i=a**b
print('a**b=',i)


a+b= 7
a-b= -3
a*b= 10
a/b= 0.4
a%b= 2
a-b 0
a**b= 32


In [ ]:
a=8
b=5
d=a !=b,
print('a !=b=',d)

a !=b= (True,)


In [ ]:
a=2
b=5
a+=b
print('a=',a)
print('b=',b)

a= 7
b= 5


In [ ]:
#special operator
a=5
b=5
d=a is b
print('a is b=',d)
d=a is not b
print('a is not b=',d)

a is b= True
a is not b= False


In [ ]:
# in and not in operator
a="HELLO"
b="1"
c=b in a
print("b in a=",c)
d=b not in a
print(" b not in a=",d)

b in a= False
 b not in a= True


In [ ]:
# input a no and check even.
a=int(input('Enter a number'))
if a%2==0:
    print('Even No')

Enter a number143


In [ ]:
str= 'python'
for i in str:
  print(i)


p
y
t
h
o
n


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
# while loop
n = i
while n<=10:
  print(n)
  n=n+1

10


In [ ]:
# To find AREA and PERIMETER
# Triangle AREA =1/2X b* h,PERIMETER=a+b+c
b=int(input('Enter b=?)'))
h=int(input('Enter h=?'))
area=0.5*b*h
print# To find AREA and PERIMETER,
#nt('AREA OF TRIANGLE=',area)
#Triangle PERIMETER=a+b+c
a=int(input('Enter a=?'))
b=int(input('Enter b=?'))
c=int(input('Enter c=?'))
perimeter=a*b*c
print('PERIMETER OF TRIANGLE=',perimeter)

Enter b=?)12
Enter h=?11
Enter a=?10
Enter b=?22
Enter c=?4
PERIMETER OF TRIANGLE= 880


In [ ]:
for var in"ABIT":
  if var=="B":
    continue
  print(var)

A
I
T


In [ ]:
for i in range(10):
  print(i)
  if i==2:
    break

0
1
2


In [ ]:
x = abs(-7.25)
print(x)

7.25


In [ ]:
list = [0,2,2]
a = all(list)
print(a)

False


In [ ]:
tuple = (0, 1, False)
a = any(tuple)
print(a)


True


In [ ]:
a = ascii("Mostly Sane")
print(a)

'Mostly Sane'


In [ ]:
a = bin(30)
print(a)

0b11110


In [ ]:
# user defind function
def show():
  print('Hello CSE')
  show()


In [ ]:
# Passing parameters in user Defind Function
def ADD(a,b):
  c=a+b
  print('SUM OF TWO NOS=',c)
ADD(10,20)


SUM OF TWO NOS= 30


In [ ]:
# Passing parameters in user Defind Function
def ADD(a,b):
  c=a+b
  print('SUM OF TWO NOS=',c)
p=int(input("Enter first no = ?"))
q=int(input("Enter second no = ?"))
ADD(p,q)


Enter first no = ?12
Enter second no = ?23
SUM OF TWO NOS= 35


In [ ]:
# using return statement in user defind function
def sumfn(n):
  s=0
  for i in range(1,n+1):
    s=s+i
  return(s)
m=int(input("Enter n=?"))
print('sum of n=',sumfn(m))

Enter n=?7
sum of n= 28


In [ ]:
list1 = ['i','LOVE','PYTHON','ABIT']
list2 = [1,2,3,4,5,6]
list3 = ['python',20,54.6,'Jyoti','a','b']

In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[2:6])

[30, 40, 50, 60]


In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[:4])

[10, 20, 30, 40]


In [ ]:
name = 'jyoti'
age = 51
is_adult = True
print(name)
print(age)

jyoti
51


In [ ]:
print('what is your name? ')

what is your name? 


In [ ]:
# Regular tetrahedron volume
import math
b=int(input('Enter b:'))
volume

In [ ]:
#Cube volume
s=int(input('Enter s:'))
volume=s*s
print('volume of a cube is=',volume)
#Cube surface area
s=int(input('Enter s:'))
surface_area=6*s*s
print('surface area of a cube is=',surface_area)

Enter s:10
volume of a cube is= 100
Enter s:21
surface area of a cube is= 2646


In [ ]:
#Cuboid volume
l=int(input('Enter l:'))
w=int(input('Enter w:'))
h=int(input('Enter h:'))
volume=l*w*h
print('volume of a cuboid is=',volume)
#Cuboid surface area
l=int(input('Enter l:'))
w=int(input('Enter w:'))
h=int(input('Enter h:'))
surface_area=(2*l*h)+(2*l*w)+(2*w*h)
print('surface area of a cuboid is=',surface_area)

Enter l:5
Enter w:8
Enter h:9
volume of a cuboid is= 360
Enter l:9
Enter w:4
Enter h:3
surface area of a cuboid is= 150


In [ ]:
# prims volume
a=int(input('Enter a:'))
h=int(input('Enter h:'))
volume=a*h
print('volume of a prism is=',volume)
a=int(input('Enter a:'))
h=int(input('Enter h'))
p=int(input('Enter p:'))
surface_area=2*a+(h*p)
print('surface area of a prism is=',surface_area)

Enter a:12
Enter h:34
volume of a prism is= 408
Enter a:4
Enter h8
Enter p:9
surface area of a prism is= 80


In [ ]:
my_list = ["apple","orange","mango","banana"]
print(my_list)

['apple', 'orange', 'mango', 'banana']


In [ ]:
print(type(23))
print(type('jyoti'))

<class 'int'>
<class 'str'>


In [ ]:
print(len('jyoti'))

5


In [ ]:
print(type('jyoti'))
print(type(23))
print(type(True))
print(type(False))


<class 'str'>
<class 'int'>
<class 'bool'>
<class 'bool'>


In [ ]:
mylist1 = ['apple','orange','banana']
mylist2 = ['app','or','ab']
mylist1.extend(mylist2)
print(mylist1)
mylist1.remove('orange')
print(mylist1)
mylist1.pop('orange')
print(mylist1)
delmylist2=('apple')
print(mylist2)



In [ ]:
mylist=['apple','orange','banana']
print(len(mylist))
yourlist=[1,4,8]
print(yourlist)
mylist1=[True,False,True,False]
print(mylist)
mix=['apple',1,2,'orange',True]
print(mix)
print(mix[-2])
print(mix[1:3])
if"apple" in mix:
  print('yes,it is in mylist')
  mylist[2]="orange"
  print(mylist)
mylist.insert(3,"kiwi")
print(mylist)
mylist.append("mango")
print(mylist)


3
[1, 4, 8]
['apple', 'orange', 'banana']
['apple', 1, 2, 'orange', True]
orange
[1, 2]
yes,it is in mylist
['apple', 'orange', 'orange']
['apple', 'orange', 'orange', 'kiwi']
['apple', 'orange', 'orange', 'kiwi', 'mango']


In [ ]:
mylist1 = ['apple','orange','banana']
for i in  mylist1:
  print(i)
  while(length>2)


In [ ]:
unsorted_list=[5,4,-3,7,99]
sorted_list=sorted(unsorted_list)
print("sorted list:",sorted_list)




sorted list: [-3, 4, 5, 7, 99]


In [ ]:
import numpy as np
data2 = [[1,2,3,4],[5,5,7,8]]
arr2 = np.array(data2)
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [ ]:
import numpy as np
data2 = [[1,2,3,4],[5,6,7,8],[55,66,76,88]]
arr2 = np.array(data2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)import numpy as np

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [55 66 76 88]]


In [ ]:
array = np.arange(0,10,2)
a

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
array = np.random.randint(0,10,(3,3))
a

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
arr = np.array([[1.,2.,3],[4.,5.,6]])
print(arr)
[(1,2,3)]
[4,5,6]


[[1. 2. 3.]
 [4. 5. 6.]]


[4, 5, 6]

In [ ]:
import numpy as np
print()


enter row size


In [ ]:
def gcd_fun(x,y):
 if(y==0):#
   return x
 else:
  return gcd_fun(y,x%y)
x =int(input("enter the first number:"))
y =int(input("enter the second number:"))
num=gcd_fun(x,y)
print("GCD of two numbers is:")
print(num) # call num


enter the first number:20
enter the second number:50
GCD of two numbers is:
10


In [ ]:
def linear_search(list1,n,key)
for i in range(0,n)
   if(list1[i] == key):
    return i
  return-1
  list 1 = [1,3,5,4,7,9]
  key = 7
  n=len(list1)
  res=linear_search(list1,n,key)
  if(res==-1):
    print("element not found")
  else:
    print("element found at index:",res)




IndentationError: unindent does not match any outer indentation level (<tokenize>, line 5)